services:
  - type: web
    name: supply-chain-game
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12